import Head from 'next/head'
import Counter from '../components/Counter'
import Header from '../components/header/Header'
import Sidebar from '../components/sidebar/Sidebar'
import {useSelector} from"react-redux"

export default function Home() {

  const isSidebarOpen = useSelector((state)=> state.theme.isSidebarOpen)
  return (
    <div >
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Counter />
      <Sidebar /> 
    </div>
  )
}
